# Generated by Django 5.0.6 on 2024-06-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fomento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_agencia', models.CharField(blank=True, max_length=255, null=True)),
                ('sigla_agencia', models.CharField(max_length=10)),
                ('valor_aportado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('AL', 'Aluno'), ('PR', 'Professor')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Pesquisadores',
            },
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orientador', models.CharField(blank=True, max_length=255, null=True)),
                ('palavras_chave', models.TextField(blank=True, null=True)),
                ('ano_inicio', models.IntegerField()),
                ('ano_conclusao', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.area')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.instituicao')),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pesquisador')),
            ],
            options={
                'verbose_name_plural': 'Formações Acadêmicas',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('EA', 'Em Andamento'), ('FI', 'Finalizado'), ('AA', 'Aguardando Aprovação'), ('CA', 'Cancelado'), ('SU', 'Suspenso'), ('OU', 'Outro')], max_length=2)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.area')),
                ('fomento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.fomento')),
                ('pesquisadores', models.ManyToManyField(to='website.pesquisador')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_producao', models.CharField(choices=[('PA', 'Patente'), ('AR', 'Artigo'), ('LI', 'Livro'), ('RE', 'Relatório'), ('OU', 'Outro')], max_length=2)),
                ('data_publicacao', models.DateField()),
                ('descricao', models.TextField()),
                ('pesquisadores', models.ManyToManyField(to='website.pesquisador')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projeto')),
            ],
            options={
                'verbose_name_plural': 'Produções',
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='website.area')),
            ],
            options={
                'verbose_name_plural': 'Subáreas',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='subareas',
            field=models.ManyToManyField(to='website.subarea'),
        ),
    ]
