# Generated by Django 5.0.6 on 2024-05-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_delete_pesquisador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('formacao', models.IntegerField(choices=[(1, 'Graduação'), (2, 'Especialização'), (3, 'MBA'), (4, 'Mestrado'), (5, 'Doutorado')])),
            ],
        ),
    ]
